@php

$vocabList = collect([
    [
        'meaning' => 'to learn, study',
        'politeForm' => 'べんきょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'benkyo',
        'verbType' => 'suru',
        'meanings' => ['learn', 'study'],
        'kanji' => [
            'word' => '勉強をします',
            'meaning' => 'to learn, study',
        ],
    ],
    [
        'meaning' => 'to investigate, inquire',
        'politeForm' => 'ちょうさをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'chousa',
        'verbType' => 'suru',
        'meanings' => ['investigate', 'inquire'],
        'kanji' => [
            'word' => '調査をします',
            'meaning' => 'to investigate, inquire',
        ],
    ],
    [
        'meaning' => 'to order (goods)',
        'politeForm' => 'ちゅうもんをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'chuumon',
        'verbType' => 'suru',
        'meanings' => ['order (goods)', 'order goods', 'order'],
        'kanji' => [
            'word' => '注文をします',
            'meaning' => 'to order (goods)',
        ],
    ],
    [
        'meaning' => 'to decrease, reduce',
        'politeForm' => 'げんしょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'genshou',
        'verbType' => 'suru',
        'meanings' => ['decrease', 'reduce'],
        'kanji' => [
            'word' => '減少をします',
            'meaning' => 'to decrease, reduce',
        ],
    ],
    [
        'meaning' => 'to announce, release',
        'politeForm' => 'はっぴょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'happyou',
        'verbType' => 'suru',
        'meanings' => ['announce', 'release'],
        'kanji' => [
            'word' => '発表をします',
            'meaning' => 'to announce, release',
        ],
    ],
    [
        'meaning' => 'to release, be on sale, launch',
        'politeForm' => 'はつばいをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'hatsubai',
        'verbType' => 'suru',
        'meanings' => ['release', 'be on sale', 'launch'],
        'kanji' => [
            'word' => '発売をします',
            'meaning' => 'to release, be on sale, launch',
        ],
    ],
    [
        'meaning' => 'to reply, answer',
        'politeForm' => 'へんじをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'henji',
        'verbType' => 'suru',
        'meanings' => ['reply', 'answer'],
        'kanji' => [
            'word' => '返事をします',
            'meaning' => 'to reply, answer',
        ],
    ],
    [
        'meaning' => 'to change',
        'politeForm' => 'へんかをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'henka',
        'verbType' => 'suru',
        'meanings' => ['change'],
        'kanji' => [
            'word' => '変化をします',
            'meaning' => 'to change',
        ],
    ],
    [
        'meaning' => 'to translate',
        'politeForm' => 'ほんやくをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'honyaku',
        'verbType' => 'suru',
        'meanings' => ['translate'],
        'kanji' => [
            'word' => '翻訳をします',
            'meaning' => 'to translate',
        ],
    ],
    [
        'meaning' => 'to report',
        'politeForm' => 'ほうこくをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'houkoku',
        'verbType' => 'suru',
        'meanings' => ['report'],
        'kanji' => [
            'word' => '報告をします',
            'meaning' => 'to report',
        ],
    ],
    [
        'meaning' => 'to print',
        'politeForm' => 'いんさつをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'insatsu',
        'verbType' => 'suru',
        'meanings' => ['print'],
        'kanji' => [
            'word' => '印刷をします',
            'meaning' => 'to print',
        ],
    ],
    [
        'meaning' => 'to develop',
        'politeForm' => 'かいはつをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kaihatsu',
        'verbType' => 'suru',
        'meanings' => ['develop'],
        'kanji' => [
            'word' => '開発をします',
            'meaning' => 'to develop',
        ],
    ],
    [
        'meaning' => 'to check, confirm',
        'politeForm' => 'かくにんをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kakunin',
        'verbType' => 'suru',
        'meanings' => ['check', 'confirm'],
        'kanji' => [
            'word' => '確認をします',
            'meaning' => 'to check, confirm',
        ],
    ],
    [
        'meaning' => 'to manage, control',
        'politeForm' => 'かんりをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kanri',
        'verbType' => 'suru',
        'meanings' => ['manage', 'control'],
        'kanji' => [
            'word' => '管理をします',
            'meaning' => 'to manage, control',
        ],
    ],
    [
        'meaning' => 'to complete',
        'politeForm' => 'かんせいをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kansei',
        'verbType' => 'suru',
        'meanings' => ['complete'],
        'kanji' => [
            'word' => '完成をします',
            'meaning' => 'to complete',
        ],
    ],
    [
        'meaning' => 'to exchange, replace',
        'politeForm' => 'こうかんをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'koukan',
        'verbType' => 'suru',
        'meanings' => ['exchange', 'replace'],
        'kanji' => [
            'word' => '交換をします',
            'meaning' => 'to exchange, replace',
        ],
    ],
    [
        'meaning' => 'to break, damage, hurt',
        'politeForm' => 'こしょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'koshou',
        'verbType' => 'suru',
        'meanings' => ['break', 'damage', 'hurt'],
        'kanji' => [
            'word' => '故障をします',
            'meaning' => 'to break, damage, hurt',
        ],
    ],
    [
        'meaning' => 'to contact, get in touch, inform',
        'politeForm' => 'れんらくをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'renraku',
        'verbType' => 'suru',
        'meanings' => ['contact', 'get in touch', 'inform'],
        'kanji' => [
            'word' => '連絡をします',
            'meaning' => 'to contact, get in touch, inform',
        ],
    ],
    [
        'meaning' => 'to practice, drill, execise, workout',
        'politeForm' => 'れんしゅうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'renshuu',
        'verbType' => 'suru',
        'meanings' => ['practice', 'drill', 'exercise', 'workout'],
        'kanji' => [
            'word' => '練習をします',
            'meaning' => 'to practice, drill, execise, workout',
        ],
    ],
    [
        'meaning' => 'to divorce',
        'politeForm' => 'りこんをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'rikon',
        'verbType' => 'suru',
        'meanings' => ['divorce'],
        'kanji' => [
            'word' => '離婚をします',
            'meaning' => 'to divorce',
        ],
    ],
    [
        'meaning' => 'to use',
        'politeForm' => 'りようをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'riyou',
        'verbType' => 'suru',
        'meanings' => ['use'],
        'kanji' => [
            'word' => '利用をします',
            'meaning' => 'to use',
        ],
    ],
    [
        'meaning' => 'to travel, make a trip',
        'politeForm' => 'りょこうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'ryokou',
        'verbType' => 'suru',
        'meanings' => ['travel', 'make a trip', 'take a trip', 'journey'],
        'kanji' => [
            'word' => '旅行をします',
            'meaning' => 'to travel, make a trip',
        ],
    ],
    [
        'meaning' => 'to cook',
        'politeForm' => 'りょうりをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'riouri',
        'verbType' => 'suru',
        'meanings' => ['cook'],
        'kanji' => [
            'word' => '料理をします',
            'meaning' => 'to cook',
        ],
    ],
    [
        'meaning' => 'to agree, support',
        'politeForm' => 'さんせいをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'sansei',
        'verbType' => 'suru',
        'meanings' => ['agree', 'support', 'approve', 'favour', 'favor'],
        'kanji' => [
            'word' => '賛成をします',
            'meaning' => 'to agree, support, favour, favor, approve',
        ],
    ],
    [
        'meaning' => 'to work',
        'politeForm' => 'しごとをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shigoto',
        'verbType' => 'suru',
        'meanings' => ['work'],
        'kanji' => [
            'word' => '仕事をします',
            'meaning' => 'to work',
        ],
    ],
    [
        'meaning' => 'to have a meal',
        'politeForm' => 'しょくじをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shokuji',
        'verbType' => 'suru',
        'meanings' => ['have a meal'],
        'kanji' => [
            'word' => '食事をします',
            'meaning' => 'to have a meal',
        ],
    ],
    [
        'meaning' => 'to go on a business trip',
        'politeForm' => 'しゅっちょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shucchou',
        'verbType' => 'suru',
        'meanings' => ['go on a business trip'],
        'kanji' => [
            'word' => '出張をします',
            'meaning' => 'to go on a business trip',
        ],
    ],
    [
        'meaning' => 'to attend, appear, be present',
        'politeForm' => 'しゅっせきをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shusseki',
        'verbType' => 'suru',
        'meanings' => ['attend', 'appear', 'be present'],
        'kanji' => [
            'word' => '出席をします',
            'meaning' => 'to attend, appear, be present',
        ],
    ],
    [
        'meaning' => 'to repair, fix, service',
        'politeForm' => 'しゅうりをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shuuri',
        'verbType' => 'suru',
        'meanings' => ['repair', 'fix', 'service'],
        'kanji' => [
            'word' => '修理をします',
            'meaning' => 'to repair, fix, service',
        ],
    ],
    [
        'meaning' => 'to consult, discuss, talk with',
        'politeForm' => 'そうだんをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'soudan',
        'verbType' => 'suru',
        'meanings' => ['consult', 'discuss', 'talk with'],
        'kanji' => [
            'word' => '相談をします',
            'meaning' => 'to consult, discuss, talk with',
        ],
    ],
    [
        'meaning' => 'to graduate',
        'politeForm' => 'そつぎょうをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'sotsugyou',
        'verbType' => 'suru',
        'meanings' => ['graduate'],
        'kanji' => [
            'word' => '卒業をします',
            'meaning' => 'to graduate',
        ],
    ],
    [
        'meaning' => 'to eat',
        'politeForm' => 'たべます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'taberu',
        'verbType' => 'ichidan',
        'meanings' => ['eat'],
        'kanji' => [
            'word' => '食べます',
            'meaning' => 'to eat',
        ],
    ],
    [
        'meaning' => 'to drink',
        'politeForm' => 'のみます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'nomu',
        'verbType' => 'godan',
        'meanings' => ['drink'],
        'kanji' => [
            'word' => '飲みます',
            'meaning' => 'to drink',
        ],
    ],
    [
        'meaning' => 'to buy',
        'politeForm' => 'かいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kau',
        'verbType' => 'godan',
        'meanings' => ['buy'],
        'kanji' => [
            'word' => '買います',
            'meaning' => 'to buy',
        ],
    ],
    [
        'meaning' => 'to watch, look, see',
        'politeForm' => 'みます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'miru',
        'verbType' => 'ichidan',
        'meanings' => ['watch', 'look', 'see'],
        'kanji' => [
            'word' => '見ます',
            'meaning' => 'to watch, look, see',
        ],
    ],
    [
        'meaning' => 'to show',
        'politeForm' => 'みせます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'miseru',
        'verbType' => 'ichidan',
        'meanings' => ['show'],
        'kanji' => [
            'word' => '見せます',
            'meaning' => 'to show',
        ],
    ],
    [
        'meaning' => 'to write, draw, paint',
        'politeForm' => 'かきます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kaku',
        'verbType' => 'godan',
        'meanings' => ['write', 'draw', 'paint'],
        'kanji' => [
            'word' => '書きます',
            'meaning' => 'to write, draw, paint',
        ],
    ],
    [
        'meaning' => 'to send',
        'politeForm' => 'おくります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'okuru',
        'verbType' => 'godan',
        'meanings' => ['send'],
        'kanji' => [
            'word' => '送ります',
            'meaning' => 'to send',
        ],
    ],
    [
        'meaning' => 'to make, produce, cook',
        'politeForm' => 'つくります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'tsukuru',
        'verbType' => 'godan',
        'meanings' => ['make', 'produce', 'cook'],
        'kanji' => [
            'word' => '作ります',
            'meaning' => 'to make, produce, cook',
        ],
    ],
    [
        'meaning' => 'to use',
        'politeForm' => 'つかいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'tsukau',
        'verbType' => 'godan',
        'meanings' => ['use'],
        'kanji' => [
            'word' => '使います',
            'meaning' => 'to use',
        ],
    ],
    [
        'meaning' => 'to go',
        'politeForm' => 'いきます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'iku',
        'verbType' => 'godan',
        'meanings' => ['go'],
        'kanji' => [
            'word' => '行きます',
            'meaning' => 'to go',
        ],
    ],
    [
        'meaning' => 'to talk, speak',
        'politeForm' => 'はなします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'hanasu',
        'verbType' => 'godan',
        'meanings' => ['talk', 'speak'],
        'kanji' => [
            'word' => '話します',
            'meaning' => 'to talk, speak',
        ],
    ],
    [
        'meaning' => 'to increase',
        'politeForm' => 'ふえます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'fueru',
        'verbType' => 'ichidan',
        'meanings' => ['increase'],
        'kanji' => [
            'word' => '増えます',
            'meaning' => 'to increase',
        ],
    ],
    [
        'meaning' => 'to decrease',
        'politeForm' => 'へります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'heru',
        'verbType' => 'godan',
        'meanings' => ['decrease'],
        'kanji' => [
            'word' => '減ります',
            'meaning' => 'to decrease',
        ],
    ],
    [
        'meaning' => 'to learn',
        'politeForm' => 'ならいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'narau',
        'verbType' => 'godan',
        'meanings' => ['learn'],
        'kanji' => [
            'word' => '習います',
            'meaning' => 'to learn',
        ],
    ],
    [
        'meaning' => 'to memorize, learn, master',
        'politeForm' => 'おぼえます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'oboeru',
        'verbType' => 'ichidan',
        'meanings' => ['memorize', 'learn', 'master'],
        'kanji' => [
            'word' => '覚えます',
            'meaning' => 'to memorize, learn, master',
        ],
    ],
    [
        'meaning' => 'to teach, inform, notice, let somebody know',
        'politeForm' => 'おしえます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'oshieru',
        'verbType' => 'ichidan',
        'meanings' => ['teach', 'inform', 'notice', 'let somebody know'],
        'kanji' => [
            'word' => '教えます',
            'meaning' => 'to teach, inform, notice, let somebody know',
        ],
    ],
    [
        'meaning' => 'to check, investigate',
        'politeForm' => 'しらべます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shiraberu',
        'verbType' => 'ichidan',
        'meanings' => ['check', 'investigate'],
        'kanji' => [
            'word' => '調べます',
            'meaning' => 'to check, investigate',
        ],
    ],
    [
        'meaning' => 'to forget',
        'politeForm' => 'わすれます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'wasureru',
        'verbType' => 'ichidan',
        'meanings' => ['forget'],
        'kanji' => [
            'word' => '忘れます',
            'meaning' => 'to forget',
        ],
    ],
    [
        'meaning' => 'to begin, start, open',
        'politeForm' => 'はじまります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'hajimaru',
        'verbType' => 'godan',
        'meanings' => ['begin', 'start', 'open'],
        'kanji' => [
            'word' => '始まります',
            'meaning' => 'to begin, start, open',
        ],
    ],
    [
        'meaning' => 'to finish, end',
        'politeForm' => 'おわります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'owaru',
        'verbType' => 'godan',
        'meanings' => ['finish', 'end'],
        'kanji' => [
            'word' => '終わります',
            'meaning' => 'to finish, end',
        ],
    ],
    [
        'meaning' => 'to open',
        'politeForm' => 'あけます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'akeru',
        'verbType' => 'ichidan',
        'meanings' => ['open', 'unwrap', 'unlock', 'empty', 'remove', 'make space'],
        'kanji' => [
            'word' => '開けます',
            'meaning' => 'to open',
        ],
    ],
    [
        'meaning' => 'to close',
        'politeForm' => 'しめます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shimeru',
        'verbType' => 'ichidan',
        'meanings' => ['close', 'shut'],
        'kanji' => [
            'word' => '閉めます',
            'meaning' => 'to close',
        ],
    ],
    [
        'meaning' => 'to win',
        'politeForm' => 'かちます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'katsu',
        'verbType' => 'godan',
        'meanings' => ['win', 'gain victory'],
        'kanji' => [
            'word' => '勝ちます',
            'meaning' => 'to win',
        ],
    ],
    [
        'meaning' => 'to lose (a game)',
        'politeForm' => 'まけます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'makeru',
        'verbType' => 'ichidan',
        'meanings' => ['lose (a game)', 'be defeated', 'succumb', 'give in', 'surrender'],
        'kanji' => [
            'word' => '負けます',
            'meaning' => 'to lose (a game)',
        ],
    ],
    [
        'meaning' => 'to turn, curve',
        'politeForm' => 'まがります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'magaru',
        'verbType' => 'godan',
        'meanings' => ['turn', 'curve', 'warp', 'wind', 'twist'],
        'kanji' => [
            'word' => '曲がります',
            'meaning' => 'to turn, curve',
        ],
    ],
    [
        'meaning' => 'to get on, ride',
        'politeForm' => 'のります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'noru',
        'verbType' => 'godan',
        'meanings' => ['get on', 'ride', 'board', 'take', 'embark', 'reach', 'go over', 'take part', 'join'],
        'kanji' => [
            'word' => '乗ります',
            'meaning' => 'to get on, ride',
        ],
    ],
    [
        'meaning' => 'to get off, descend, go down, disembark, dismount, step down, give up, quit',
        'politeForm' => 'おります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'oriru',
        'verbType' => 'ichidan',
        'meanings' => ['get off', 'descend', 'go down', 'disembark', 'dismount', 'retire', 'step down', 'give up', 'quit'],
        'kanji' => [
            'word' => '降ります',
            'meaning' => 'to get off, descend, go down, disembark, dismount, step down, give up, quit',
        ],
    ],
    [
        'meaning' => 'to translate',
        'politeForm' => 'やくします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'yakusu',
        'verbType' => 'godan',
        'meanings' => ['translate', 'interpret'],
        'kanji' => [
            'word' => '訳します',
            'meaning' => 'to translate',
        ],
    ],
    [
        'meaning' => 'to lie down, go to bed',
        'politeForm' => 'ねます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'neru',
        'verbType' => 'ichidan',
        'meanings' => ['lie down', ' goto bed', 'sleep (with someone)', 'sleep'],
        'kanji' => [
            'word' => '寝ます',
            'meaning' => 'to lie down, go to bed',
        ],
    ],
    [
        'meaning' => 'to get up, wake up, happen, occur',
        'politeForm' => 'おきます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'okiru',
        'verbType' => 'ichidan',
        'meanings' => ['get up', 'wake up', 'happen', 'occur', 'stay awake'],
        'kanji' => [
            'word' => '起きます',
            'meaning' => 'to get up, wake up, happen, occur',
        ],
    ],
    [
        'meaning' => 'to break, damage, hurt',
        'politeForm' => 'こわれます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kowareru',
        'verbType' => 'ichidan',
        'meanings' => ['break', 'damage', 'hurt'],
        'kanji' => [
            'word' => '壊れます',
            'meaning' => 'to break, damage, hurt',
        ],
    ],
    [
        'meaning' => 'to repair, fix, cure, correct, heal',
        'politeForm' => 'なおします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'naosu',
        'verbType' => 'godan',
        'meanings' => ['repair', 'fix', 'cure', 'heal', 'correct'],
        'kanji' => [
            'word' => '直します',
            'meaning' => 'to repair, fix, cure, correct, heal',
        ],
    ],
    [
        'meaning' => 'to borrow, rent, hire, have a loan',
        'politeForm' => 'かります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kariru',
        'verbType' => 'ichidan',
        'meanings' => ['borrow', 'rent', 'hire', 'have a loan'],
        'kanji' => [
            'word' => '借ります',
            'meaning' => 'to borrow, rent, hire, have a loan',
        ],
    ],
    [
        'meaning' => 'to go up, rise',
        'politeForm' => 'あがります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'agaru',
        'verbType' => 'godan',
        'meanings' => ['go up', 'rise', 'come up', 'ascend', 'be raised', 'come in', 'go in', 'enter', 'go in', 'increase', 'improve', 'make progress'],
        'kanji' => [
            'word' => '上がります',
            'meaning' => 'to go up, rise, come up, ascend, be raised, come in, go in, enter, increase, improve, make progress',
        ],
    ],
    [
        'meaning' => 'to go down, drop',
        'politeForm' => 'さがります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'sagaru',
        'verbType' => 'godan',
        'meanings' => ['go down', 'drop', 'come down', 'fall', 'sink', 'get lower', 'dangle'],
        'kanji' => [
            'word' => '下がります',
            'meaning' => 'to go down, drop, come down, fall, sink, get lower, dangle',
        ],
    ],
    [
        'meaning' => 'to sit, have a seat',
        'politeForm' => 'すわります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'suwaru',
        'verbType' => 'godan',
        'meanings' => ['sit', 'have a seat', 'squat', 'hold still'],
        'kanji' => [
            'word' => '座ります',
            'meaning' => 'to sit, have a seat, squat, hold still',
        ],
    ],
    [
        'meaning' => 'to wash, cleanse, rinse, purify, investigate, inquire into',
        'politeForm' => 'あらいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'arau',
        'verbType' => 'godan',
        'meanings' => ['wash', 'cleanse', 'rinse', 'purify', 'invesitgate', 'inquire into'],
        'kanji' => [
            'word' => '洗います',
            'meaning' => 'to wash, cleanse, rinse, purify, investigate, inquire into',
        ],
    ],
    [
        'meaning' => 'to grill, bake, roast, toast',
        'politeForm' => 'やきます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'yaku',
        'verbType' => 'godan',
        'meanings' => ['grill', 'bake', 'roast', 'toast', 'burn', 'heat', 'heat up', 'barbecue'],
        'kanji' => [
            'word' => '焼きます',
            'meaning' => 'to grill, bake, roast, toast, burn, heat up, barbecue',
        ],
    ],
    [
        'meaning' => 'to cut',
        'politeForm' => 'きります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kiru',
        'verbType' => 'godan',
        'meanings' => ['cut', 'cut through', 'perform (surgery)', 'sever', 'turn off'],
        'kanji' => [
            'word' => '切ります',
            'meaning' => 'to cut, sever, perform (surgery), turn off',
        ],
    ],
    [
        'meaning' => 'to come',
        'politeForm' => 'きます*',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kuru',
        'verbType' => 'irregular',
        'meanings' => ['come', 'arrive', 'approach'],
        'kanji' => [
            'word' => '来ます',
            'meaning' => 'to come',
        ],
    ],
    [
        'meaning' => 'to take off (shoes, clothes)',
        'politeForm' => 'ぬぎます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'nugu',
        'verbType' => 'godan',
        'meanings' => ['take off clothes', 'undress', 'take off shoes', 'strip'],
        'kanji' => [
            'word' => '脱ぎます',
            'meaning' => 'to take off (shoes, clothes), undress, strip',
        ],
    ],
    [
        'meaning' => 'to do, play (something), carry out, perform',
        'politeForm' => 'します*',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'suru',
        'verbType' => 'irregular',
        'meanings' => ['do', 'play (something)', 'carry out', 'perform'],
        'kanji' => [
            'word' => 'します',
            'meaning' => 'to do, play (something), carry out, perform',
        ],
    ],
    [
        'meaning' => 'to phone, call (by phone)',
        'politeForm' => 'でんわをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'denwa',
        'verbType' => 'suru',
        'meanings' => ['phone', 'call', 'ring'],
        'kanji' => [
            'word' => '電話をします',
            'meaning' => 'to phone, call (by phone), ring',
        ],
    ],
    [
        'meaning' => 'to oppose, to be against',
        'politeForm' => 'はんたいをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'hantai',
        'verbType' => 'suru',
        'meanings' => ['oppose', 'be against'],
        'kanji' => [
            'word' => '反対をします',
            'meaning' => 'to oppose, to be against',
        ],
    ],
    [
        'meaning' => 'to get a job',
        'politeForm' => 'しゅうしょくをします',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'shuushoku',
        'verbType' => 'suru',
        'meanings' => ['get a job'],
        'kanji' => [
            'word' => '就職をします',
            'meaning' => 'to get a job',
        ],
    ],
    [
        'meaning' => 'to meet / to match, fit',
        'politeForm' => 'あいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'au',
        'verbType' => 'godan',
        'meanings' => ['meet', 'match', 'fit'],
        'kanji' => [
            'word' => '会います',
            'meaning' => 'to meet / to match, fit',
        ],
    ],
    [
        'meaning' => 'return',
        'politeForm' => 'かえります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'kaeru',
        'verbType' => 'godan',
        'meanings' => ['return'],
        'kanji' => [
            'word' => '帰ります',
            'meaning' => 'return',
        ],
    ],
    [
        'meaning' => 'to have, be, at, exist (inanimate object)',
        'politeForm' => 'あります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'aru',
        'verbType' => 'godan',
        'meanings' => ['have', 'be', 'at', 'exist (inanimate object)'],
        'kanji' => [
            'word' => 'あります',
            'meaning' => 'to have, be, at, exist (inanimate object)',
        ],
    ],
    [
        'meaning' => 'to have, be at, exist (animate object)',
        'politeForm' => 'います',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'iru',
        'verbType' => 'ichidan',
        'meanings' => ['have', 'be at', 'exist (animate object)', 'be', 'exist'],
        'kanji' => [
            'word' => 'います',
            'meaning' => 'to have, be at, exist (animate object)',
        ],
    ],
    [
        'meaning' => 'to stop',
        'politeForm' => 'とまります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'tomaru',
        'verbType' => 'godan',
        'meanings' => ['stop', 'perch', 'hault'],
        'kanji' => [
            'word' => '止まります',
            'meaning' => 'to stop',
        ],
    ],
    [
        'meaning' => 'to stay (the night), lodge',
        'politeForm' => 'とまります',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'tomaru',
        'verbType' => 'godan',
        'meanings' => ['stay (the night)', 'lodge'],
        'kanji' => [
            'word' => '泊まります',
            'meaning' => 'to stop / to stay (the night), lodge',
        ],
    ],
    [
        'meaning' => 'to raise, lift up',
        'politeForm' => 'あげます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'ageru',
        'verbType' => 'ichidan',
        'meanings' => ['raise', 'lift up'],
        'kanji' => [
            'word' => '上げます',
            'meaning' => 'to raise, lift up',
        ],
    ],
    [
        'meaning' => 'to recieve, be given',
        'politeForm' => 'もらいます',
        'hasLearned' => false,
        'shouldKnow' => false,
        'timesWrong' => 0,
        'timesRight' => 0,
        'stem' => 'morau',
        'verbType' => 'godan',
        'meanings' => ['recieve', 'be given'],
        'kanji' => [
            'word' => '貰います',
            'meaning' => 'to recieve, be given',
        ],
    ],
]);

$vobabList = json_encode($vocabList);
@endphp
<div class="container w-full flex flex-col justify-center items-center" data-controller="game autokana"
    data-game-vocabulary="{{ json_encode($vocabList) }}">
    <div class="flex flex-col mb-8">
        <div class="top flex w-full flex-col items-center justify-center">
            <div class="notification" id="notification-container"></div>
            <div class="info"></div>
            <div id="display" class="flex w-full flex-col items-center justify-center"></div>
        </div>
    </div>
    <div class="bg-gray-100 rounded-lg w-full">
        <input type="text" id="input" class="p-2 input w-full h-100" placeholder="Enter the verb..." />
    </div>
    <div class="py-4">
        <div class="flex flex-row gap-2 justify-evenly">
            {{-- <button class="btn reset bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
                id="reset-button" onclick="handleReset()">
                Reset Game ( clear local storage )
            </button>
            <button class="btn forgot bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
                id="forgot-button" onclick="handleForgetButton()">
                I don't remember
            </button> --}}
            <button class="btn submit bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
                id="submit-button" onclick="handleSubmitButton()">
                Submit
            </button>
            <!--       <div class="button toggleMode" id="mode-button" onclick="handleChangeMode()">Toggle Mode</div> -->
        </div>
        <div class="hint">Type '?' to take a loss and learn the word</div>
        <div class="hint">Press 'Enter' to submit</div>
        <div class="hint">
            Get the same word right more than the number of times you've
            gotten it wrong + 3 will allow you to get more words
        </div>
    </div>
</div>
