<x-wrapper>
    <x-layout.container>
        <x-layout.row>
            <x-layout.col>
                <div>
                    Home
                </div>
            </x-layout.col>
        </x-layout.row>
    </x-layout.container>
</x-wrapper>
